// <auto-generated>
// Rewired Constants
// This list was generated on 2024/2/4 16:20:31
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace LFramework.LInput {
    public static partial class RewiredConsts {
        public static partial class Action {
            // Default
            [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Horizontal")]
            public const int Move_Horizontal = 0;
            
            [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Vertical")]
            public const int Move_Vertical = 1;
            
            [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Fire")]
            public const int Fire = 2;
            
        }
        public static partial class Category {
            public const int Default = 0;
            
        }
        public static partial class Layout {
            public static partial class Joystick {
                public const int Default = 0;
                
            }
            public static partial class Keyboard {
                public const int Default = 0;
                
                public const int Player_0 = 1;
                
                public const int Player_1 = 2;
                
            }
            public static partial class Mouse {
                public const int Default = 0;
                
            }
            public static partial class CustomController {
                public const int Default = 0;
                
            }
        }
        public static partial class Player {
            [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
            public const int System = 9999999;
            
            [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
            public const int Player0 = 0;
            
        }
        public static partial class CustomController {
        }
        public static partial class LayoutManagerRuleSet {
        }
        public static partial class MapEnablerRuleSet {
        }
    }
}
