
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class GlobalTable
{
    private readonly System.Collections.Generic.Dictionary<string, GlobalConfig> _dataMap;
    private readonly System.Collections.Generic.List<GlobalConfig> _dataList;
    
    public GlobalTable(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, GlobalConfig>();
        _dataList = new System.Collections.Generic.List<GlobalConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GlobalConfig _v;
            _v = GlobalConfig.DeserializeGlobalConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, GlobalConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<GlobalConfig> DataList => _dataList;

    public GlobalConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GlobalConfig Get(string key) => _dataMap[key];
    public GlobalConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

