
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class GlobalConfig : Luban.BeanBase
{
    public GlobalConfig(ByteBuf _buf) 
    {
        Name = _buf.ReadString();
        ValueStr = _buf.ReadString();
        ValueInt = _buf.ReadInt();
    }

    public static GlobalConfig DeserializeGlobalConfig(ByteBuf _buf)
    {
        return new GlobalConfig(_buf);
    }

    public readonly string Name;
    public readonly string ValueStr;
    public readonly int ValueInt;
   
    public const int __ID__ = -958250779;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "ValueStr:" + ValueStr + ","
        + "ValueInt:" + ValueInt + ","
        + "}";
    }
}

}
