
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Threading.Tasks;

namespace cfg
{
public partial class Tables
{
    public item.TbItem TbItem {get;private set;}

    public Tables() { }

    public async Task LoadAsync(System.Func<string, Task<ByteBuf>> loader)
    {
        TbItem = new item.TbItem(await loader("item_tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
    }
}

}
