//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Threading.Tasks;


namespace cfg
{
   
public sealed class Tables
{
    public AITable AITable {get; private set; }

    public Tables() { }
    
    public async Task LoadAsync(System.Func<string, Task<ByteBuf>> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        AITable = new AITable(await loader("aitable")); 
        tables.Add("AITable", AITable);

        AITable.Resolve(tables); 
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        AITable.TranslateText(translator); 
    }
}

}
