
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class LocalizationTable
{
    private readonly System.Collections.Generic.Dictionary<string, LocalizationConfig> _dataMap;
    private readonly System.Collections.Generic.List<LocalizationConfig> _dataList;
    
    public LocalizationTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, LocalizationConfig>();
        _dataList = new System.Collections.Generic.List<LocalizationConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LocalizationConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LocalizationConfig.DeserializeLocalizationConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, LocalizationConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<LocalizationConfig> DataList => _dataList;

    public LocalizationConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LocalizationConfig Get(string key) => _dataMap[key];
    public LocalizationConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

