
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GlobalConfig : Luban.BeanBase
{
    public GlobalConfig(JSONNode _buf) 
    {
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["ValueStr"].IsString) { throw new SerializationException(); }  ValueStr = _buf["ValueStr"]; }
        { if(!_buf["ValueInt"].IsNumber) { throw new SerializationException(); }  ValueInt = _buf["ValueInt"]; }
    }

    public static GlobalConfig DeserializeGlobalConfig(JSONNode _buf)
    {
        return new GlobalConfig(_buf);
    }

    public readonly string Name;
    public readonly string ValueStr;
    public readonly int ValueInt;
   
    public const int __ID__ = -958250779;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "ValueStr:" + ValueStr + ","
        + "ValueInt:" + ValueInt + ","
        + "}";
    }
}

}
